package com.pojo;
// Generated 8 Aug, 2018 7:00:59 AM by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Position generated by hbm2java
 */
public class Position implements java.io.Serializable {

	private Integer pid;
	private String position;
	private Set sponsers = new HashSet(0);

	public Position() {
	}

	public Position(String position, Set sponsers) {
		this.position = position;
		this.sponsers = sponsers;
	}

	public Integer getPid() {
		return this.pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public Set getSponsers() {
		return this.sponsers;
	}

	public void setSponsers(Set sponsers) {
		this.sponsers = sponsers;
	}

}
